name: GitHub Workflow Demo

# Whenever a push is detected on this repo, runs:
on: [push]
# can also do things like [pull] [merge] [push pull]

# What do we want our workflow to do
jobs: 
  # Name of job
  actions_demo: 
    # What type of VM do we want it to run on?
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello, GitHub!"
      - run: ls
      - uses: actions/checkout@v3
      - run: ls
      - run: chmod +x CICD_Scripts/CICD_test.sh
      - run: ./CICD_Scripts/CICD_test.sh
      - run: echo "First script run!"
      - run: chmod +x CICD_Scripts/CICD_Script_2.sh
      - run: ./CICD_Scripts/CICD_Script_2.sh
      - run: echo "Second script run!"

